### ISSUE TITLE
Notes from meeting w/ Yong

### ISSUE THREAD

**Issue by bnickodemus** [osu-cascades/beaver-counseling#136]
create 1 page memorandum including:
- uses cases
- what is done (signatures, reporting, top issues like hippa, etc.)
- whats stopping the clinic from using the app now
- incomplete issues
- what are next steps
- print out memorandum for Erika

to do:
- complete 1 page memorandum
- meet w/ Erika and discuss memorandum
- don’t implement new features

4 things to do:
- add tests
- clean up code
- document what you have
- baa

**Comment by ybakos** [comment]
This doesn't belong here in GH.
