### ISSUE TITLE
Upgrade to Ruby 2.5.1 and Rails 5.2.1

### ISSUE THREAD

**Issue by Radabaugh** [osu-cascades/beaver-counseling#138]

**Comment by ybakos** [comment]
@Radabaugh @krishanchopra23 I will have this done by Thursday, Oct. 18.

**Comment by ybakos** [comment]
@Radabaugh @krishanchopra23 This is done, on the _development_ branch.

(BTW, you have been working w/ the development branch, right? 😄 )
