### ISSUE TITLE
Client intake form Yes/No check boxes formatting

### ISSUE THREAD

**Issue by krishanchopra23** [osu-cascades/beaver-counseling#147]
Should be one not both.

**Comment by krishanchopra23** [comment]
The no checkbox is being pushed to a new line on some devices.

**Comment by Radabaugh** [comment]
> Should be one not both.

I don't remember what this means.

**Comment by Radabaugh** [comment]
When viewing on the Amazon Fire tablets the clinic is using, the `May we leave a message?` and `May we send you emails?` check boxes are formatted poorly. The `No` check box appears on its own line below the `Yes` checkbox. This probably also affects the `Past Client?` check boxes.
