### ISSUE TITLE
Missing Procfile and Puma config per Heroku

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-counseling#3]
Notice that when you deploy there are warnings. Squelch them.

See "Procfile" and "Config" here (only, ignore the rest): https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

/cc @wilsonja1 @bnickodemus

**Comment by bnickodemus** [comment]
We tried following the tutorial and it failed to work on windows

**Comment by ybakos** [comment]
@wilsonja1 Let's take a look at this so I understand what the problem is. Low priority.

**Comment by ybakos** [comment]
I see it now. The [docs](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server) state that this:

`workers Integer(ENV['WEB_CONCURRENCY'] || 2)`

"Multi process mode does not work if you are using JRuby or Windows because the JVM and Windows do not support processes. Omit this line from your config if you are using JRuby or Windows."

So we can do something like:

`workers(Integer(ENV['WEB_CONCURRENCY'] || 2)) unless Rails.env.development?`

**Comment by wilsonja1** [comment]
We will give that a stab
