### ISSUE TITLE
ClientsController: use "before filter" to reduce duplication

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-counseling#45]
```
@clients = Client.all
@users = User.all
```

http://guides.rubyonrails.org/action_controller_overview.html

**Comment by bnickodemus** [comment]
From my understanding using before filter for the sake of DRY is not always best practice
http://craftingruby.com/posts/2015/05/31/dont-use-before-action-to-load-data.html

https://blog.ragnarson.com/2015/09/30/problems-with-typical-rails-controllers-and-before-actions.html
What are the before actions good for
The only justified usecase for before actions should be something that doesn't have any side effects concerning the state - example would be redirecting to sign in page when the user is not logged in. It doesn't brake the main flow of the action into several pieces, doesn't set any instance variables and works more like a guard clause.

Maybe I should add a helper method instead?

**Comment by bnickodemus** [comment]
From my understanding using before filter for the sake of DRY is not always best practice
http://craftingruby.com/posts/2015/05/31/dont-use-before-action-to-load-data.html

https://blog.ragnarson.com/2015/09/30/problems-with-typical-rails-controllers-and-before-actions.html
What are the before actions good for
The only justified usecase for before actions should be something that doesn't have any side effects concerning the state - example would be redirecting to sign in page when the user is not logged in. It doesn't brake the main flow of the action into several pieces, doesn't set any instance variables and works more like a guard clause.

Maybe I should add a helper method instead?

**Comment by bnickodemus** [comment]
https://stackoverflow.com/questions/16519828/rails-4-before-filter-vs-before-action

**Comment by ybakos** [comment]
I like the argument here against 'before filters' that tend to hide instance variables from the body of relevant methods. But don't overengineer it. Go ahead and close this if you wish.
