### ISSUE TITLE
Cannot create user

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-counseling#52]
When I visit:

![screen shot 2017-11-30 at 4 43 45 am](https://user-images.githubusercontent.com/5502/33431399-13341bfa-d589-11e7-94eb-26449a9b128c.png)

I then get an error:

![screen shot 2017-11-30 at 4 43 41 am](https://user-images.githubusercontent.com/5502/33431411-1ad1b6e2-d589-11e7-8124-c4749d39df2e.png)

**Comment by bnickodemus** [comment]
There wasn't an admin in the database so it was trying to create a client with a foreign key that did not exist. We have fixed this issue and added admin to the seeds.rb file.
