### ISSUE TITLE
URGENT: remove production db password from repo

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-counseling#89]
Never ever, ever commit credentials to a repository. You production database is exposed, and you just allowed the world to access all of the counseling data in the database. This is a huge ethical responsibility.

Remove the password immediately from database.yml, and learn how to use environment variables.
ALSO CHANGE THE production database password.

**Comment by wilsonja1** [comment]
Password is changed. I'll fix the file

**Comment by bnickodemus** [comment]
Should we use the gem dotenv or Figaro to hide the password?
I've used both before and know that they both work
