### ISSUE TITLE
Update devise, etc.

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/beaver-counseling#90]
![screen shot 2018-04-04 at 7 09 35 am](https://user-images.githubusercontent.com/5502/38312662-2c2bdc96-37d7-11e8-8e13-38545f65aece.png)

**Comment by bnickodemus** [comment]
Did my previous commit fix the issue?
It looks like collaborators do NOT receive security alerts:
https://help.github.com/articles/permission-levels-for-a-user-account-repository/
